### PR TITLE
Add deep emailHashProperty fields e.g. Avatar.options.emailHashProperty = profile.emailHash

### PR DESCRIPTION
**Pull request by TheAncientGoat**
Also adds customizable fields for initials generation, and cwohlman's custom profile_picture field

### CODE REVIEW

**Comment by SachaG** [comment]
Oh, I hadn't seen this PR, I ended up [submitting one for the same thing](https://github.com/bengott/meteor-avatar/pull/66). Hopefully one or the other can get merged soon!

**Comment by SachaG** [comment]
Can you give an example of how you'd use `initialsFirst` and `initialsLast`?

And I like the `profilePictureProperty` property, good idea.

**Comment by TheAncientGoat** [comment]
The config I'm currently using with my featureset; didn't realize the pull request is actually pulling in all the commits I made, guess I should update it with a better description

```
@Avatar.options = {
  fallbackType: "initials"
  emailHashProperty: 'profile.email_hash'
  initialsFirst: 'first_name' //refers to profile.first_name
  initialsLast: 'last_name' //refers to profile.last_name
  profilePictureProperty: 'profile_picture' //refers to profile.profile_picture
};
```

**Comment by SachaG** [comment]
Hmm, `initialsFirst` and `initialsLast` is a confusing naming scheme. I think we should call them `firstNameProperty` and `lastNameProperty` instead. 

I also adapted @cwohlman's code and merged it in, so I'll close this PR. Maybe you can submit a new one just for the firstName/lastName thing? Although make sure you use `getDescendantProp` so we're not tied down to the `profile` object.

**Pull request closed without merging**
