### PR TITLE
Remove onerror handler

### PR DESCRIPTION
**Pull request by CarlQLange**
I'd rather have the errors show up in my console. Also allows for slightly-more-likely-to-work avatars loading after userId change or whatever.

While using this for a toy app, it began to really bug me that I couldn't see why the image wouldn't display. I'm aware that this breaks falling back to initials - however, surely it would be better to explicitly handle this elsewhere, rather than in the template?

Anyway, I'd be surprised if you merged this. I just forked it so I could use it myself, and thought I may as well put in the PR. Can give a better rationale if you really actually care.

### CODE REVIEW

**Comment by SachaG** [comment]
I think that's a good rationale, but this would have to be coupled with another way to make the initials fallback work.

**Comment by CarlQLange** [comment]
By default be `display:none`, and an onsuccesshandler that makes the image display? That way we don't squash the error. But I dunno, it's late.

**Comment by SachaG** [comment]
That might work. Can you add it to the PR so I can test it?

That being said I think we *do* want to squash 404s in the console. Otherwise you just get a ton of them.

**Comment by CarlQLange** [comment]
Sure, but it'll be a few days. Suddenly swamped with Paying Work so my toys will have to wait :) Sorry about that!

**Comment by SachaG** [comment]
No problem :)

**Comment by CarlQLange** [comment]
I'm afraid I didn't get around to this, and I'm about to leave for the Camino del Norte for the next 6 weeks, so I can't do this work in time to make any difference. Shouldn't take long anyway, for whoever wants to pick it up!

**Comment by rodrigok** [comment]
I think that this PR is more appropriate #69

**Comment by bengott** [comment]
cleaning up and closing PRs..

**Pull request closed without merging**
