### PR TITLE
Disable Gravatar while using a local server

### PR DESCRIPTION
**Pull request by GerryR**
I have added a new option "gravatarEnabled" that is false by default in localhost and true otherwise. Furthermore you can choose if using the Gravatar or not anywhere. Hope it helps!

### CODE REVIEW

**Comment by syzer** [comment]
+1

**Comment by SachaG** [comment]
I will probably fork this package and republish it under my own name, it doesn't seem to be actively maintained anymore. If I do that you can probably just resubmit that PR to the new repo?

**Comment by syzer** [comment]
@SachaG please do it, and i may be able to help you with merging some issues / pull requests

**Comment by voidale** [comment]
+1 on a new fork...

**Comment by SachaG** [comment]
Done: https://atmospherejs.com/utilities/avatar

I created a new "utilities" organization, this way the package is not tied down to my name and it'll be easier to transfer ownership in the future if I'm not able to maintain it.

**Comment by SachaG** [comment]
What was the thinking behind this? Why disable Gravatars locally?

**Comment by GerryR** [comment]
From Readme:
Note that Gravatar's default option requires a publicly accessible URL, so it won't work when your app is running on localhost and you're using either the included package default image or a custom defaultImageUrl that is a relative path. It will work fine once deployed though.

This pull request aims to solve this issue in development and it is compatible with previous version, plus it gives the possibility to disable gravatar in case someone does not like it.

**Comment by rodcisal** [comment]
+1 to implement this, please

**Comment by bengott** [comment]
cleaning up and closing PRs..

**Pull request closed without merging**
